### ISSUE TITLE
Error with Rmarkdown

### ISSUE THREAD

**Issue by daSilva5** [PredictiveEcology/Require#108]
Hey guys,
I am using Require with Rmarkdown
I have the following chunk 

```{r}
if (!require("Require")) {install.packages("Require")}
library(Require)
Require::Require(c("here","tidyverse","RefManageR"))

```

And I get the following error if I try to knit to html:

Error in `getCRANrepos()`:
! Please set a CRAN mirror
Backtrace:
 1. Require::Require(c("here", "tidyverse", "RefManageR"), repos = "http://cran.us.r-project.org")
 2. Require::pkgDep(...)
 3. Require:::getAvailablePackagesIfNeeded(...)
 4. Require:::available.packagesCached(...)
 5. Require::getCRANrepos(repos)

I have tried to provide an url:

```{r}
if (!require("Require")) {install.packages("Require")}
library(Require)
Require::Require(c("here","tidyverse","RefManageR"),repos='http://cran.us.r-project.org')

```

Did not work.

What can I do here?
Thanks

**Comment by CeresBarros** [comment]
I've also had issues with "http://cran.us.r-project.org/" in the past. One solution that worked for me was to pass
`repos = "http://cran.r-project.org"` 

Another, was to set the default CRAN repo in a setup chunk at the start of the .Rmd, so that you don't have to pass it to `Require(..., repos)`

```
options(repos = list(CRAN = "http://cran.r-project.org"))
```

Also, if you load `Require` with `library(Require)` you don't need to append the package name with `::` :)

**Comment by achubaty** [comment]
You should also be using https in the url instead of plain http

**Comment by daSilva5** [comment]
Hi, 
Thank you all.
setting  options(repos = list(CRAN = "http://cran.r-project.org"))    was what worked for me.
