### ISSUE TITLE
GitHub API rate limits?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Require#46]
With the removal of the `remotes` package as a dependency, how are GitHub Personal Access Tokens currently used to query/fetch packages from GitHub?

- [x] confirm if/how env var `GITHUB_PAT` is being used;
- [x] improve testing in projects using "vanilla" R session (specfically without loading `.Renviron` to get pre-stared `GITHUB_PAT` -- would a user hit rate limits for some projects without a PAT?;
- [x] provide feedback to the user if, e.g., a certain number of GitHub packages need to be queried/fetched in a `Require()` or `pkgDeps()` call -- check for the env var and tell them how to set one up for when it's needed via message. This could also be useful in `setup()`.
- [x] export this PAT-check function so it can be use e.g., in `SpaDES.project` templates as part of starndard workflow setup.

**Comment by achubaty** [comment]
related: #2 (if GITHUB_PAT is not used, then can't install from private repos)

**Comment by eliotmcintire** [comment]
There is currently no "PAT-check function". The use of GITHUB_PAT is bundled within `downloadFileMasterMainAuth` function.  This function deals with both the GITHUB_PAT issue and the transition between `main` and `master` on Github... meaning it will try "the other" branch if e.g., `master` is specified, and the download hits a `404`.  

I have renamed it to use a `dot` prefix (`.downloadFileMasterMainAuth`) because using it will imply fairly advanced uses. As of `Require (>=0.2.6.9020)` it is exported. Will be shortly in `development` branch.
